language: c
compiler: gcc
script: make all
before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq libmysqlclient-dev cproto

env:
  global:
   - secure: "HHSPWzZPgxpM/oqL60FiUQGziRnaUO6NcZMS7SqZhnqE7PyvKy4K8UgfwZXmfALHaIkHm081uJw1FIv8pMuLQgCLijPq86+9mNxkHqoYV5Hv9s34AAxE9SaMZkELK1toq/phPTmxQM2zh0FoLhaJen9uwUmdHoUE/YleG7MC4mI="

addons:
  coverity_scan:
    project:
      name: "bmybbs/bmybbs"
      description: "Build submitted via Travis CI"
    notification_email:
      secure: "YlN18ZO9i4Hr+PKuZlfRxSLLvWA/XURFF5STN8PGhoonzL0kpyUnCNFsI9YHB+tDw8b8NUqh3rdHabfbbYIwmxikFHHm00rGcV3JB/haKFw9/3gRIeTvJarryIKJsPME1BufVaG6vsuGqd7y7n8ENdOaxdfx5CgAJz67xdgcgzE="
    build_command_prepend: "make clean; make prepend"
    build_command: "make core"
    branch_pattern: master

