language: c
compiler: gcc
script: make all
before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq libmysqlclient-dev cproto

env:
  global:
   - secure: "HLgw588BO8dmHtMWP+UFnd34UC74OBeefm3AKT/C8Vdw0ApSQ1YNTQmoVyy7YEhFpfVDnSvinAqGq0tDJTWEtmHH5ah4x3dIQ2MmKo9ibLW/NT3oULbOEH7bxNkJN4OZTnvQVjebLeVQNIsPlekVHTn2odTI5PKSF/F2/yZt3AA="

addons:
  coverity_scan:
    project:
      name: "bmybbs/bmybbs"
      description: "Build submitted via Travis CI"
    notification:
      secure: "YlN18ZO9i4Hr+PKuZlfRxSLLvWA/XURFF5STN8PGhoonzL0kpyUnCNFsI9YHB+tDw8b8NUqh3rdHabfbbYIwmxikFHHm00rGcV3JB/haKFw9/3gRIeTvJarryIKJsPME1BufVaG6vsuGqd7y7n8ENdOaxdfx5CgAJz67xdgcgzE="
    build_command_prepend: "make clean"
    build_command: "cd ythtlib; make; cd ../libythtbbs; make; cd ../src; make; cd ../nju09; make"
    branch_pattern: master

